# Site settings
title: HCI TC-2 Website
email: peoconno@bowdoin.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a website for a fake artist for my HCI class
baseurl: http://paigeemanuelle.github.io # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  paigeemanuelle


# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Links to include in menu
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Music
    url: /music
  - title: Journal
    url: /journal
